### ISSUE TITLE
Task list:

### ISSUE THREAD

**Issue by BlackFIlms** [BlackFIlms/LearningC#2]
- [x] Write first task (mathSquareOfTheTwoNumbers)
- [x] Learn Basic concepts into C++
- [x] Record in the project Basic concepts into C++   
*   REInstall VS on the work computer
- [x] Learn custom functions
- [x] Record in the project custom functions
- [x] Learn IO functions
- [x] Record in the project IO functions
- [x] Learn conditionals and loops
- [x] Record in the project conditionals and loops
- [x] Write task #2: (FindTheRequiredVolumeOfWater)
- [x] Write task #3: (conStairs)
- [ ] Learn classes and objects
- [ ] Record in the project classes and objects
- [ ] Learn arrays and strings
- [ ] Record in the project arrays and strings
- [ ] Learn more classes
- [ ] Record in the project more classes
- [ ] Learn Ineritance and polymorphism
- [ ] Record in the project Ineritance and polymorphism
- [ ] Learn structs, enums, exceptions and files
- [ ] Record in the project structs, enums, exceptions and files
- [ ] Write First serious project
- [ ] **Congratulations!**
